{"hierarchy":{"paths":[["doc:\/\/org.swift.tspl\/documentation\/The-Swift-Programming-Language"]]},"sections":[],"identifier":{"url":"doc:\/\/org.swift.tspl\/documentation\/The-Swift-Programming-Language\/ErrorHandling","interfaceLanguage":"swift"},"metadata":{"title":"Error Handling"},"abstract":[{"text":"Respond to and recover from errors.","type":"text"}],"kind":"article","primaryContentSections":[{"kind":"content","content":[{"type":"paragraph","inlineContent":[{"type":"emphasis","inlineContent":[{"type":"text","text":"Error handling"}]},{"type":"text","text":" is the process of responding to"},{"type":"text","text":" "},{"text":"and recovering from error conditions in your program.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Swift provides first-class support for"},{"type":"text","text":" "},{"text":"throwing, catching, propagating, and manipulating","type":"text"},{"type":"text","text":" "},{"text":"recoverable errors at runtime.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Some operations"},{"type":"text","text":" "},{"type":"text","text":"aren’t guaranteed to always complete execution or produce a useful output."},{"text":" ","type":"text"},{"text":"Optionals are used to represent the absence of a value,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"but when an operation fails,"},{"text":" ","type":"text"},{"type":"text","text":"it’s often useful to understand what caused the failure,"},{"type":"text","text":" "},{"type":"text","text":"so that your code can respond accordingly."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"As an example, consider the task of reading and processing data from a file on disk."},{"type":"text","text":" "},{"type":"text","text":"There are a number of ways this task can fail, including"},{"type":"text","text":" "},{"text":"the file not existing at the specified path,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"the file not having read permissions, or"},{"type":"text","text":" "},{"type":"text","text":"the file not being encoded in a compatible format."},{"type":"text","text":" "},{"text":"Distinguishing among these different situations","type":"text"},{"text":" ","type":"text"},{"text":"allows a program to resolve some errors","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"and to communicate to the user any errors it can’t resolve."}]},{"content":[{"inlineContent":[{"type":"text","text":"Error handling in Swift interoperates with error handling patterns"},{"text":" ","type":"text"},{"type":"text","text":"that use the "},{"code":"NSError","type":"codeVoice"},{"text":" class in Cocoa and Objective-C.","type":"text"},{"text":" ","type":"text"},{"text":"For more information about this class,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"see "},{"type":"reference","identifier":"https:\/\/developer.apple.com\/documentation\/swift\/cocoa_design_patterns\/handling_cocoa_errors_in_swift","isActive":true},{"type":"text","text":"."}],"type":"paragraph"}],"style":"note","type":"aside","name":"Note"},{"level":2,"anchor":"Representing-and-Throwing-Errors","type":"heading","text":"Representing and Throwing Errors"},{"type":"paragraph","inlineContent":[{"type":"text","text":"In Swift, errors are represented by"},{"type":"text","text":" "},{"type":"text","text":"values of types that conform to the "},{"code":"Error","type":"codeVoice"},{"text":" protocol.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"This empty protocol indicates that a type"},{"text":" ","type":"text"},{"type":"text","text":"can be used for error handling."}]},{"type":"paragraph","inlineContent":[{"text":"Swift enumerations are particularly well suited to modeling","type":"text"},{"text":" ","type":"text"},{"text":"a group of related error conditions,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"with associated values allowing for additional information"},{"type":"text","text":" "},{"type":"text","text":"about the nature of an error to be communicated."},{"type":"text","text":" "},{"text":"For example, here’s how you might represent the error conditions","type":"text"},{"type":"text","text":" "},{"type":"text","text":"of operating a vending machine inside a game:"}]},{"syntax":"swift","type":"codeListing","code":["enum VendingMachineError: Error {","    case invalidSelection","    case insufficientFunds(coinsNeeded: Int)","    case outOfStock","}"]},{"inlineContent":[{"type":"text","text":"Throwing an error lets you indicate that something unexpected happened"},{"type":"text","text":" "},{"type":"text","text":"and the normal flow of execution can’t continue."},{"type":"text","text":" "},{"text":"You use a ","type":"text"},{"code":"throw","type":"codeVoice"},{"type":"text","text":" statement to throw an error."},{"type":"text","text":" "},{"type":"text","text":"For example,"},{"type":"text","text":" "},{"type":"text","text":"the following code throws an error to indicate"},{"type":"text","text":" "},{"type":"text","text":"that five additional coins are needed by the vending machine:"}],"type":"paragraph"},{"syntax":"swift","code":["throw VendingMachineError.insufficientFunds(coinsNeeded: 5)"],"type":"codeListing"},{"level":2,"type":"heading","text":"Handling Errors","anchor":"Handling-Errors"},{"type":"paragraph","inlineContent":[{"type":"text","text":"When an error is thrown,"},{"text":" ","type":"text"},{"type":"text","text":"some surrounding piece of code must be responsible"},{"text":" ","type":"text"},{"type":"text","text":"for handling the error —"},{"text":" ","type":"text"},{"type":"text","text":"for example, by correcting the problem,"},{"type":"text","text":" "},{"text":"trying an alternative approach,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"or informing the user of the failure."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"There are four ways to handle errors in Swift."},{"type":"text","text":" "},{"type":"text","text":"You can propagate the error from a function to the code that calls that function,"},{"text":" ","type":"text"},{"text":"handle the error using a ","type":"text"},{"code":"do","type":"codeVoice"},{"type":"text","text":"-"},{"code":"catch","type":"codeVoice"},{"type":"text","text":" statement,"},{"text":" ","type":"text"},{"text":"handle the error as an optional value,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"or assert that the error will not occur."},{"text":" ","type":"text"},{"text":"Each approach is described in a section below.","type":"text"}]},{"inlineContent":[{"type":"text","text":"When a function throws an error,"},{"text":" ","type":"text"},{"type":"text","text":"it changes the flow of your program,"},{"type":"text","text":" "},{"type":"text","text":"so it’s important that you can quickly identify places in your code that can throw errors."},{"text":" ","type":"text"},{"type":"text","text":"To identify these places in your code, write the "},{"code":"try","type":"codeVoice"},{"type":"text","text":" keyword —"},{"type":"text","text":" "},{"type":"text","text":"or the "},{"type":"codeVoice","code":"try?"},{"text":" or ","type":"text"},{"code":"try!","type":"codeVoice"},{"text":" variation —","type":"text"},{"type":"text","text":" "},{"text":"before a piece of code that calls a function, method, or initializer that can throw an error.","type":"text"},{"text":" ","type":"text"},{"text":"These keywords are described in the sections below.","type":"text"}],"type":"paragraph"},{"type":"aside","content":[{"inlineContent":[{"text":"Error handling in Swift resembles exception handling in other languages,","type":"text"},{"text":" ","type":"text"},{"text":"with the use of the ","type":"text"},{"code":"try","type":"codeVoice"},{"type":"text","text":", "},{"type":"codeVoice","code":"catch"},{"text":" and ","type":"text"},{"code":"throw","type":"codeVoice"},{"text":" keywords.","type":"text"},{"type":"text","text":" "},{"text":"Unlike exception handling in many languages —","type":"text"},{"type":"text","text":" "},{"type":"text","text":"including Objective-C —"},{"type":"text","text":" "},{"text":"error handling in Swift doesn’t involve unwinding the call stack,","type":"text"},{"type":"text","text":" "},{"text":"a process that can be computationally expensive.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"As such, the performance characteristics"},{"text":" ","type":"text"},{"type":"text","text":"of a "},{"type":"codeVoice","code":"throw"},{"type":"text","text":" statement"},{"text":" ","type":"text"},{"text":"are comparable to those of a ","type":"text"},{"code":"return","type":"codeVoice"},{"text":" statement.","type":"text"}],"type":"paragraph"}],"style":"note","name":"Note"},{"text":"Propagating Errors Using Throwing Functions","anchor":"Propagating-Errors-Using-Throwing-Functions","level":3,"type":"heading"},{"inlineContent":[{"type":"text","text":"To indicate that a function, method, or initializer can throw an error,"},{"type":"text","text":" "},{"type":"text","text":"you write the "},{"code":"throws","type":"codeVoice"},{"type":"text","text":" keyword in the function’s declaration"},{"text":" ","type":"text"},{"text":"after its parameters.","type":"text"},{"type":"text","text":" "},{"text":"A function marked with ","type":"text"},{"code":"throws","type":"codeVoice"},{"text":" is called a ","type":"text"},{"type":"emphasis","inlineContent":[{"type":"text","text":"throwing function"}]},{"text":".","type":"text"},{"type":"text","text":" "},{"text":"If the function specifies a return type,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"you write the "},{"type":"codeVoice","code":"throws"},{"type":"text","text":" keyword before the return arrow ("},{"code":"->","type":"codeVoice"},{"text":").","type":"text"}],"type":"paragraph"},{"code":["func canThrowErrors() throws -> String","","func cannotThrowErrors() -> String"],"type":"codeListing","syntax":"swift"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A throwing function propagates errors that are thrown inside of it"},{"text":" ","type":"text"},{"text":"to the scope from which it’s called.","type":"text"}]},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Only throwing functions can propagate errors."},{"type":"text","text":" "},{"type":"text","text":"Any errors thrown inside a nonthrowing function"},{"type":"text","text":" "},{"text":"must be handled inside the function.","type":"text"}]}],"type":"aside","name":"Note"},{"type":"paragraph","inlineContent":[{"text":"In the example below,","type":"text"},{"type":"text","text":" "},{"text":"the ","type":"text"},{"type":"codeVoice","code":"VendingMachine"},{"text":" class has a ","type":"text"},{"type":"codeVoice","code":"vend(itemNamed:)"},{"type":"text","text":" method"},{"type":"text","text":" "},{"type":"text","text":"that throws an appropriate "},{"type":"codeVoice","code":"VendingMachineError"},{"text":" ","type":"text"},{"text":"if the requested item isn’t available,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"is out of stock,"},{"text":" ","type":"text"},{"type":"text","text":"or has a cost that exceeds the current deposited amount:"}]},{"code":["struct Item {","    var price: Int","    var count: Int","}","","class VendingMachine {","    var inventory = [","        \"Candy Bar\": Item(price: 12, count: 7),","        \"Chips\": Item(price: 10, count: 4),","        \"Pretzels\": Item(price: 7, count: 11)","    ]","    var coinsDeposited = 0","","    func vend(itemNamed name: String) throws {","        guard let item = inventory[name] else {","            throw VendingMachineError.invalidSelection","        }","","        guard item.count > 0 else {","            throw VendingMachineError.outOfStock","        }","","        guard item.price <= coinsDeposited else {","            throw VendingMachineError.insufficientFunds(coinsNeeded: item.price - coinsDeposited)","        }","","        coinsDeposited -= item.price","","        var newItem = item","        newItem.count -= 1","        inventory[name] = newItem","","        print(\"Dispensing \\(name)\")","    }","}"],"type":"codeListing","syntax":"swift"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The implementation of the "},{"type":"codeVoice","code":"vend(itemNamed:)"},{"type":"text","text":" method"},{"type":"text","text":" "},{"text":"uses ","type":"text"},{"code":"guard","type":"codeVoice"},{"text":" statements to exit the method early and throw appropriate errors","type":"text"},{"type":"text","text":" "},{"text":"if any of the requirements for purchasing a snack aren’t met.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Because a "},{"code":"throw","type":"codeVoice"},{"text":" statement immediately transfers program control,","type":"text"},{"text":" ","type":"text"},{"text":"an item will be vended only if all of these requirements are met.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Because the "},{"type":"codeVoice","code":"vend(itemNamed:)"},{"type":"text","text":" method propagates any errors it throws,"},{"type":"text","text":" "},{"text":"any code that calls this method must either handle the errors —","type":"text"},{"type":"text","text":" "},{"type":"text","text":"using a "},{"type":"codeVoice","code":"do"},{"text":"-","type":"text"},{"type":"codeVoice","code":"catch"},{"text":" statement, ","type":"text"},{"type":"codeVoice","code":"try?"},{"text":", or ","type":"text"},{"code":"try!","type":"codeVoice"},{"type":"text","text":"—"},{"type":"text","text":" "},{"type":"text","text":"or continue to propagate them."},{"type":"text","text":" "},{"type":"text","text":"For example,"},{"text":" ","type":"text"},{"type":"text","text":"the "},{"type":"codeVoice","code":"buyFavoriteSnack(person:vendingMachine:)"},{"type":"text","text":" in the example below"},{"text":" ","type":"text"},{"type":"text","text":"is also a throwing function,"},{"type":"text","text":" "},{"type":"text","text":"and any errors that the "},{"type":"codeVoice","code":"vend(itemNamed:)"},{"text":" method throws will","type":"text"},{"type":"text","text":" "},{"text":"propagate up to the point where the ","type":"text"},{"type":"codeVoice","code":"buyFavoriteSnack(person:vendingMachine:)"},{"text":" function is called.","type":"text"}]},{"code":["let favoriteSnacks = [","    \"Alice\": \"Chips\",","    \"Bob\": \"Licorice\",","    \"Eve\": \"Pretzels\",","]","func buyFavoriteSnack(person: String, vendingMachine: VendingMachine) throws {","    let snackName = favoriteSnacks[person] ?? \"Candy Bar\"","    try vendingMachine.vend(itemNamed: snackName)","}"],"type":"codeListing","syntax":"swift"},{"inlineContent":[{"type":"text","text":"In this example,"},{"text":" ","type":"text"},{"type":"text","text":"the "},{"code":"buyFavoriteSnack(person: vendingMachine:)","type":"codeVoice"},{"type":"text","text":" function looks up a given person’s favorite snack"},{"type":"text","text":" "},{"text":"and tries to buy it for them by calling the ","type":"text"},{"code":"vend(itemNamed:)","type":"codeVoice"},{"text":" method.","type":"text"},{"text":" ","type":"text"},{"text":"Because the ","type":"text"},{"type":"codeVoice","code":"vend(itemNamed:)"},{"type":"text","text":" method can throw an error,"},{"type":"text","text":" "},{"text":"it’s called with the ","type":"text"},{"code":"try","type":"codeVoice"},{"type":"text","text":" keyword in front of it."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Throwing initializers can propagate errors in the same way as throwing functions."},{"text":" ","type":"text"},{"text":"For example,","type":"text"},{"text":" ","type":"text"},{"text":"the initializer for the ","type":"text"},{"type":"codeVoice","code":"PurchasedSnack"},{"type":"text","text":" structure in the listing below"},{"text":" ","type":"text"},{"type":"text","text":"calls a throwing function as part of the initialization process,"},{"text":" ","type":"text"},{"type":"text","text":"and it handles any errors that it encounters by propagating them to its caller."}]},{"type":"codeListing","syntax":"swift","code":["struct PurchasedSnack {","    let name: String","    init(name: String, vendingMachine: VendingMachine) throws {","        try vendingMachine.vend(itemNamed: name)","        self.name = name","    }","}"]},{"type":"heading","text":"Handling Errors Using Do-Catch","level":3,"anchor":"Handling-Errors-Using-Do-Catch"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You use a "},{"type":"codeVoice","code":"do"},{"type":"text","text":"-"},{"code":"catch","type":"codeVoice"},{"text":" statement to handle errors","type":"text"},{"type":"text","text":" "},{"text":"by running a block of code.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"If an error is thrown by the code in the "},{"type":"codeVoice","code":"do"},{"type":"text","text":" clause,"},{"text":" ","type":"text"},{"type":"text","text":"it’s matched against the "},{"type":"codeVoice","code":"catch"},{"type":"text","text":" clauses"},{"text":" ","type":"text"},{"type":"text","text":"to determine which one of them can handle the error."}]},{"type":"paragraph","inlineContent":[{"text":"Here is the general form of a ","type":"text"},{"type":"codeVoice","code":"do"},{"type":"text","text":"-"},{"type":"codeVoice","code":"catch"},{"type":"text","text":" statement:"}]},{"code":["do {","    try <#expression#>","    <#statements#>","} catch <#pattern 1#> {","    <#statements#>","} catch <#pattern 2#> where <#condition#> {","    <#statements#>","} catch <#pattern 3#>, <#pattern 4#> where <#condition#> {","    <#statements#>","} catch {","    <#statements#>","}"],"syntax":"swift","type":"codeListing"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You write a pattern after "},{"type":"codeVoice","code":"catch"},{"type":"text","text":" to indicate what errors"},{"type":"text","text":" "},{"type":"text","text":"that clause can handle."},{"type":"text","text":" "},{"type":"text","text":"If a "},{"code":"catch","type":"codeVoice"},{"type":"text","text":" clause doesn’t have a pattern,"},{"text":" ","type":"text"},{"type":"text","text":"the clause matches any error"},{"text":" ","type":"text"},{"text":"and binds the error to a local constant named ","type":"text"},{"code":"error","type":"codeVoice"},{"type":"text","text":"."},{"text":" ","type":"text"},{"text":"For more information about pattern matching,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"see "},{"identifier":"doc:\/\/org.swift.tspl\/documentation\/The-Swift-Programming-Language\/Patterns","isActive":true,"type":"reference"},{"type":"text","text":"."}]},{"inlineContent":[{"type":"text","text":"For example, the following code matches against all three cases"},{"type":"text","text":" "},{"text":"of the ","type":"text"},{"code":"VendingMachineError","type":"codeVoice"},{"type":"text","text":" enumeration."}],"type":"paragraph"},{"code":["var vendingMachine = VendingMachine()","vendingMachine.coinsDeposited = 8","do {","    try buyFavoriteSnack(person: \"Alice\", vendingMachine: vendingMachine)","    print(\"Success! Yum.\")","} catch VendingMachineError.invalidSelection {","    print(\"Invalid Selection.\")","} catch VendingMachineError.outOfStock {","    print(\"Out of Stock.\")","} catch VendingMachineError.insufficientFunds(let coinsNeeded) {","    print(\"Insufficient funds. Please insert an additional \\(coinsNeeded) coins.\")","} catch {","    print(\"Unexpected error: \\(error).\")","}","\/\/ Prints \"Insufficient funds. Please insert an additional 2 coins.\""],"syntax":"swift","type":"codeListing"},{"type":"paragraph","inlineContent":[{"type":"text","text":"In the above example,"},{"text":" ","type":"text"},{"type":"text","text":"the "},{"type":"codeVoice","code":"buyFavoriteSnack(person:vendingMachine:)"},{"type":"text","text":" function is called in a "},{"code":"try","type":"codeVoice"},{"text":" expression,","type":"text"},{"type":"text","text":" "},{"text":"because it can throw an error.","type":"text"},{"text":" ","type":"text"},{"text":"If an error is thrown,","type":"text"},{"text":" ","type":"text"},{"text":"execution immediately transfers to the ","type":"text"},{"code":"catch","type":"codeVoice"},{"type":"text","text":" clauses,"},{"type":"text","text":" "},{"type":"text","text":"which decide whether to allow propagation to continue."},{"text":" ","type":"text"},{"type":"text","text":"If no pattern is matched, the error gets caught by the final "},{"code":"catch","type":"codeVoice"},{"text":" ","type":"text"},{"text":"clause and is bound to a local ","type":"text"},{"type":"codeVoice","code":"error"},{"text":" constant.","type":"text"},{"type":"text","text":" "},{"text":"If no error is thrown,","type":"text"},{"text":" ","type":"text"},{"text":"the remaining statements in the ","type":"text"},{"type":"codeVoice","code":"do"},{"type":"text","text":" statement are executed."}]},{"inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"catch"},{"text":" clauses don’t have to handle every possible error","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"that the code in the "},{"code":"do","type":"codeVoice"},{"type":"text","text":" clause can throw."},{"text":" ","type":"text"},{"type":"text","text":"If none of the "},{"type":"codeVoice","code":"catch"},{"text":" clauses handle the error,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"the error propagates to the surrounding scope."},{"text":" ","type":"text"},{"text":"However, the propagated error","type":"text"},{"text":" ","type":"text"},{"text":"must be handled by ","type":"text"},{"type":"emphasis","inlineContent":[{"type":"text","text":"some"}]},{"type":"text","text":" surrounding scope."},{"text":" ","type":"text"},{"text":"In a nonthrowing function,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"an enclosing "},{"code":"do","type":"codeVoice"},{"type":"text","text":"-"},{"type":"codeVoice","code":"catch"},{"text":" statement","type":"text"},{"type":"text","text":" "},{"type":"text","text":"must handle the error."},{"text":" ","type":"text"},{"type":"text","text":"In a throwing function,"},{"type":"text","text":" "},{"type":"text","text":"either an enclosing "},{"code":"do","type":"codeVoice"},{"text":"-","type":"text"},{"type":"codeVoice","code":"catch"},{"type":"text","text":" statement"},{"text":" ","type":"text"},{"type":"text","text":"or the caller"},{"type":"text","text":" "},{"type":"text","text":"must handle the error."},{"type":"text","text":" "},{"text":"If the error propagates to the top-level scope","type":"text"},{"type":"text","text":" "},{"type":"text","text":"without being handled,"},{"type":"text","text":" "},{"type":"text","text":"you’ll get a runtime error."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"For example, the above example can be written so any"},{"type":"text","text":" "},{"type":"text","text":"error that isn’t a "},{"type":"codeVoice","code":"VendingMachineError"},{"text":" is instead","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"caught by the calling function:"}]},{"code":["func nourish(with item: String) throws {","    do {","        try vendingMachine.vend(itemNamed: item)","    } catch is VendingMachineError {","        print(\"Couldn't buy that from the vending machine.\")","    }","}","","do {","    try nourish(with: \"Beet-Flavored Chips\")","} catch {","    print(\"Unexpected non-vending-machine-related error: \\(error)\")","}","\/\/ Prints \"Couldn't buy that from the vending machine.\""],"type":"codeListing","syntax":"swift"},{"inlineContent":[{"type":"text","text":"In the "},{"type":"codeVoice","code":"nourish(with:)"},{"type":"text","text":" function,"},{"type":"text","text":" "},{"text":"if ","type":"text"},{"type":"codeVoice","code":"vend(itemNamed:)"},{"type":"text","text":" throws an error that’s"},{"text":" ","type":"text"},{"type":"text","text":"one of the cases of the "},{"type":"codeVoice","code":"VendingMachineError"},{"type":"text","text":" enumeration,"},{"type":"text","text":" "},{"code":"nourish(with:)","type":"codeVoice"},{"type":"text","text":" handles the error by printing a message."},{"type":"text","text":" "},{"text":"Otherwise,","type":"text"},{"text":" ","type":"text"},{"code":"nourish(with:)","type":"codeVoice"},{"type":"text","text":" propagates the error to its call site."},{"text":" ","type":"text"},{"type":"text","text":"The error is then caught by the general "},{"type":"codeVoice","code":"catch"},{"text":" clause.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"Another way to catch several related errors","type":"text"},{"type":"text","text":" "},{"text":"is to list them after ","type":"text"},{"code":"catch","type":"codeVoice"},{"type":"text","text":", separated by commas."},{"text":" ","type":"text"},{"text":"For example:","type":"text"}],"type":"paragraph"},{"type":"codeListing","syntax":"swift","code":["func eat(item: String) throws {","    do {","        try vendingMachine.vend(itemNamed: item)","    } catch VendingMachineError.invalidSelection, VendingMachineError.insufficientFunds, VendingMachineError.outOfStock {","        print(\"Invalid selection, out of stock, or not enough money.\")","    }","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"eat(item:)"},{"type":"text","text":" function lists the vending machine errors to catch,"},{"type":"text","text":" "},{"text":"and its error text corresponds to the items in that list.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"If any of the three listed errors are thrown,"},{"type":"text","text":" "},{"text":"this ","type":"text"},{"type":"codeVoice","code":"catch"},{"type":"text","text":" clause handles them by printing a message."},{"text":" ","type":"text"},{"text":"Any other errors are propagated to the surrounding scope,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"including any vending-machine errors that might be added later."}]},{"type":"heading","text":"Converting Errors to Optional Values","level":3,"anchor":"Converting-Errors-to-Optional-Values"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You use "},{"type":"codeVoice","code":"try?"},{"type":"text","text":" to handle an error by converting it to an optional value."},{"type":"text","text":" "},{"text":"If an error is thrown while evaluating the ","type":"text"},{"code":"try?","type":"codeVoice"},{"type":"text","text":" expression,"},{"type":"text","text":" "},{"type":"text","text":"the value of the expression is "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"For example,"},{"type":"text","text":" "},{"type":"text","text":"in the following code "},{"code":"x","type":"codeVoice"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"y"},{"text":" have the same value and behavior:","type":"text"}]},{"code":["func someThrowingFunction() throws -> Int {","    \/\/ ...","}","","let x = try? someThrowingFunction()","","let y: Int?","do {","    y = try someThrowingFunction()","} catch {","    y = nil","}"],"syntax":"swift","type":"codeListing"},{"type":"paragraph","inlineContent":[{"type":"text","text":"If "},{"type":"codeVoice","code":"someThrowingFunction()"},{"text":" throws an error,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"the value of "},{"type":"codeVoice","code":"x"},{"type":"text","text":" and "},{"type":"codeVoice","code":"y"},{"text":" is ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Otherwise, the value of "},{"type":"codeVoice","code":"x"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"y"},{"text":" is the value that the function returned.","type":"text"},{"text":" ","type":"text"},{"text":"Note that ","type":"text"},{"type":"codeVoice","code":"x"},{"type":"text","text":" and "},{"type":"codeVoice","code":"y"},{"text":" are an optional of whatever type ","type":"text"},{"code":"someThrowingFunction()","type":"codeVoice"},{"text":" returns.","type":"text"},{"type":"text","text":" "},{"text":"Here the function returns an integer, so ","type":"text"},{"type":"codeVoice","code":"x"},{"type":"text","text":" and "},{"type":"codeVoice","code":"y"},{"type":"text","text":" are optional integers."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Using "},{"code":"try?","type":"codeVoice"},{"type":"text","text":" lets you write concise error handling code"},{"text":" ","type":"text"},{"text":"when you want to handle all errors in the same way.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"For example,"},{"type":"text","text":" "},{"type":"text","text":"the following code"},{"type":"text","text":" "},{"text":"uses several approaches to fetch data,","type":"text"},{"type":"text","text":" "},{"text":"or returns ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" if all of the approaches fail.","type":"text"}]},{"code":["func fetchData() -> Data? {","    if let data = try? fetchDataFromDisk() { return data }","    if let data = try? fetchDataFromServer() { return data }","    return nil","}"],"type":"codeListing","syntax":"swift"},{"level":3,"text":"Disabling Error Propagation","type":"heading","anchor":"Disabling-Error-Propagation"},{"type":"paragraph","inlineContent":[{"text":"Sometimes you know a throwing function or method","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"won’t, in fact, throw an error at runtime."},{"text":" ","type":"text"},{"type":"text","text":"On those occasions,"},{"text":" ","type":"text"},{"text":"you can write ","type":"text"},{"type":"codeVoice","code":"try!"},{"text":" before the expression to disable error propagation","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"and wrap the call in a runtime assertion that no error will be thrown."},{"text":" ","type":"text"},{"text":"If an error actually is thrown, you’ll get a runtime error.","type":"text"}]},{"inlineContent":[{"text":"For example, the following code uses a ","type":"text"},{"type":"codeVoice","code":"loadImage(atPath:)"},{"text":" function,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"which loads the image resource at a given path"},{"type":"text","text":" "},{"type":"text","text":"or throws an error if the image can’t be loaded."},{"text":" ","type":"text"},{"text":"In this case, because the image is shipped with the application,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"no error will be thrown at runtime,"},{"text":" ","type":"text"},{"type":"text","text":"so it’s appropriate to disable error propagation."}],"type":"paragraph"},{"syntax":"swift","type":"codeListing","code":["let photo = try! loadImage(atPath: \".\/Resources\/John Appleseed.jpg\")"]},{"level":2,"text":"Specifying Cleanup Actions","anchor":"Specifying-Cleanup-Actions","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"You use a ","type":"text"},{"type":"codeVoice","code":"defer"},{"text":" statement to execute a set of statements","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"just before code execution leaves the current block of code."},{"text":" ","type":"text"},{"text":"This statement lets you do any necessary cleanup","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"that should be performed regardless"},{"type":"text","text":" "},{"text":"of ","type":"text"},{"type":"emphasis","inlineContent":[{"type":"text","text":"how"}]},{"text":" execution leaves the current block of code —","type":"text"},{"type":"text","text":" "},{"type":"text","text":"whether it leaves because an error was thrown"},{"type":"text","text":" "},{"type":"text","text":"or because of a statement such as "},{"code":"return","type":"codeVoice"},{"text":" or ","type":"text"},{"type":"codeVoice","code":"break"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"For example, you can use a "},{"type":"codeVoice","code":"defer"},{"type":"text","text":" statement"},{"type":"text","text":" "},{"type":"text","text":"to ensure that file descriptors are closed"},{"type":"text","text":" "},{"type":"text","text":"and manually allocated memory is freed."}]},{"type":"paragraph","inlineContent":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"defer"},{"type":"text","text":" statement defers execution until the current scope is exited."},{"type":"text","text":" "},{"text":"This statement consists of the ","type":"text"},{"code":"defer","type":"codeVoice"},{"type":"text","text":" keyword and the statements to be executed later."},{"type":"text","text":" "},{"text":"The deferred statements may not contain any code","type":"text"},{"text":" ","type":"text"},{"text":"that would transfer control out of the statements,","type":"text"},{"text":" ","type":"text"},{"text":"such as a ","type":"text"},{"code":"break","type":"codeVoice"},{"type":"text","text":" or a "},{"type":"codeVoice","code":"return"},{"type":"text","text":" statement,"},{"text":" ","type":"text"},{"type":"text","text":"or by throwing an error."},{"text":" ","type":"text"},{"type":"text","text":"Deferred actions are executed in the reverse of"},{"text":" ","type":"text"},{"text":"the order that they’re written in your source code.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"That is, the code in the first "},{"type":"codeVoice","code":"defer"},{"type":"text","text":" statement executes last,"},{"type":"text","text":" "},{"type":"text","text":"the code in the second "},{"code":"defer","type":"codeVoice"},{"text":" statement executes second to last,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"and so on."},{"text":" ","type":"text"},{"text":"The last ","type":"text"},{"type":"codeVoice","code":"defer"},{"type":"text","text":" statement in source code order executes first."}]},{"code":["func processFile(filename: String) throws {","    if exists(filename) {","        let file = open(filename)","        defer {","            close(file)","        }","        while let line = try file.readline() {","            \/\/ Work with the file.","        }","        \/\/ close(file) is called here, at the end of the scope.","    }","}"],"syntax":"swift","type":"codeListing"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The above example uses a "},{"type":"codeVoice","code":"defer"},{"type":"text","text":" statement"},{"type":"text","text":" "},{"text":"to ensure that the ","type":"text"},{"code":"open(_:)","type":"codeVoice"},{"type":"text","text":" function"},{"type":"text","text":" "},{"text":"has a corresponding call to ","type":"text"},{"type":"codeVoice","code":"close(_:)"},{"text":".","type":"text"}]},{"inlineContent":[{"text":"You can use a ","type":"text"},{"type":"codeVoice","code":"defer"},{"text":" statement","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"even when no error handling code is involved."},{"type":"text","text":" "},{"type":"text","text":"For more information,"},{"text":" ","type":"text"},{"type":"text","text":"see "},{"identifier":"doc:\/\/org.swift.tspl\/documentation\/The-Swift-Programming-Language\/ControlFlow#Deferred-Actions","type":"reference","isActive":true},{"type":"text","text":"."}],"type":"paragraph"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://org.swift.tspl/documentation/The-Swift-Programming-Language/Patterns":{"url":"\/documentation\/the-swift-programming-language\/patterns","identifier":"doc:\/\/org.swift.tspl\/documentation\/The-Swift-Programming-Language\/Patterns","abstract":[{"text":"Match and destructure values.","type":"text"}],"kind":"article","role":"article","type":"topic","title":"Patterns"},"https://developer.apple.com/documentation/swift/cocoa_design_patterns/handling_cocoa_errors_in_swift":{"type":"link","url":"https:\/\/developer.apple.com\/documentation\/swift\/cocoa_design_patterns\/handling_cocoa_errors_in_swift","title":"Handling Cocoa Errors in Swift","identifier":"https:\/\/developer.apple.com\/documentation\/swift\/cocoa_design_patterns\/handling_cocoa_errors_in_swift","titleInlineContent":[{"text":"Handling Cocoa Errors in Swift","type":"text"}]},"doc://org.swift.tspl/documentation/The-Swift-Programming-Language/ControlFlow#Deferred-Actions":{"type":"topic","identifier":"doc:\/\/org.swift.tspl\/documentation\/The-Swift-Programming-Language\/ControlFlow#Deferred-Actions","title":"Deferred Actions","url":"\/documentation\/the-swift-programming-language\/controlflow#Deferred-Actions","kind":"section","abstract":[]},"doc://org.swift.tspl/documentation/The-Swift-Programming-Language":{"kind":"article","url":"\/documentation\/the-swift-programming-language","identifier":"doc:\/\/org.swift.tspl\/documentation\/The-Swift-Programming-Language","type":"topic","role":"collection","title":"The Swift Programming Language (5.9)","abstract":[]}}}